### ISSUE TITLE
Add bill deblasio to NYC reps

### ISSUE THREAD

**Issue by johnCbogil** [johnCbogil/voices-ios#18]
lol

**Comment by johnCbogil** [comment]
Hey @krishnascoding , can you store bill de blasios information in a plist file instead of a dictionary? Sry to change the requirement on you, I gave it some thought and realized that it's safer to store hard coded data like that in a plist file than in code. You can add the plist file to the "supporting files" folder of the project. Thanks

**Comment by krishnascoding** [comment]
@johnCbogil ok sounds good, I'll store it in a plist instead of a dictionary

**Comment by krishnascoding** [comment]
Hey @johnCbogil I've got a few questions for you before pushing anything to github.. but I'm basically done with the deBlasio ticket item (I think).. Here are the questions, you can call or text if you'd prefer to answer that way. Or we can do it in person when we next meet. 
He has two Twitter accounts @BilldeBlasio or @NYCMayorsOffice . Preference of which to use?
Can’t find an email for de Blasio. only web form http://www.nyc.gov/html/static/pages/officeofthemayor/contact.shtml . What should I do about that?
He doesn’t have a District, district Address, or borough since he’s mayor. So I just listed New York City in the district field and the legAddress and districtAddress are the same City Hall address. Is that ok or should I list it some other way?

**Comment by johnCbogil** [comment]
@krishnascoding Hey those are totally fair questions I wouldn't expect you to have answers to so:
- I think we should use @billdeblasio, what do you think? I prefer @billdeblasio bc I was reading the tweets from the other twitter account and they don't feel very personal, they feel dry almost robotic and we want our users to feel like they're contacting a human being. But lmk what you think, maybe i'm wrong. 
- You can leave the email blank, but check the city council file to see how we're handling empty email values. Idr if empty email values are null or are just empty strings such as @" ". 
- The values you chose for distrct, address, etc are fine for now. I'll change them when the time comes.

**Comment by krishnascoding** [comment]
@johnCbogil pushed this item - should be good to go, check it out

**Comment by johnCbogil** [comment]
Hey @krishnascoding, you can go ahead and create a pull request to the master branch. Don't worry about breaking anything, a pull request is simply a request that says "hey john, i made some changes that i think you should add to master, take a look at the changes and if it looks alright, then you should merge it with master". 

Also, "closing" an issue is the final step after we've merged to master. So i'm going to reopen the issue for now. 

**One more thing**: please pull the latest version of master and merge master into this branch before you create the pull request. Otherwise there will likely be merge conflicts and github will not allow me to approve the request. 

I'm excited to look at your code tho!
